apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: cap
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: muzakkirsaifi/springboot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
          - name: MONGODB_HOST
            value: "mongodb-0.mongodb"
          - name: MONGODB_PORT
            value: "27017"
